In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Integer Enconding

In [2]:
docs= ['go india',
       'india india',
       'hip hip hurray',
       'jeetega bhai jeetega india jeetega',
       'bharat mata ki jai',
       'sachin sachin',
       'Kohali kOhali',
       'modi ji ke jai',
       'jai hind'
      ]

In [4]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='mahavir')

In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
tokenizer.word_index

{'mahavir': 1,
 'india': 2,
 'jeetega': 3,
 'jai': 4,
 'hip': 5,
 'sachin': 6,
 'kohali': 7,
 'go': 8,
 'hurray': 9,
 'bhai': 10,
 'bharat': 11,
 'mata': 12,
 'ki': 13,
 'modi': 14,
 'ji': 15,
 'ke': 16,
 'hind': 17}

In [9]:
tokenizer.document_count

9

In [10]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jai', 3),
             ('sachin', 2),
             ('kohali', 2),
             ('modi', 1),
             ('ji', 1),
             ('ke', 1),
             ('hind', 1)])

In [11]:
sequences = tokenizer.texts_to_sequences(docs)

In [12]:
sequences

[[8, 2],
 [2, 2],
 [5, 5, 9],
 [3, 10, 3, 2, 3],
 [11, 12, 13, 4],
 [6, 6],
 [7, 7],
 [14, 15, 16, 4],
 [4, 17]]

In [14]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')

In [15]:
sequences

array([[ 8,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 5,  5,  9,  0,  0],
       [ 3, 10,  3,  2,  3],
       [11, 12, 13,  4,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [14, 15, 16,  4,  0],
       [ 4, 17,  0,  0,  0]])

# Using Integer Enconding on imdb dataset of keras

In [18]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Flatten

In [19]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 5s 0us/step


In [20]:
x_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [21]:
x_train.shape

(25000,)

In [22]:
x_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [24]:
print(len(x_train[0]))
print(len(x_train[1]))

218
189


In [25]:
x_train = pad_sequences(x_train,padding='post',maxlen = 50)
x_test = pad_sequences(x_test,padding='post',maxlen = 50)

In [26]:
x_train.shape

(25000, 50)

In [27]:
x_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32])

In [28]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [32]:
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5


782/782 [==============================] - 11s 13ms/step - loss: 0.6993 - accuracy: 0.5044 - val_loss: 0.6946 - val_accuracy: 0.5024
Epoch 2/5
782/782 [==============================] - 9s 11ms/step - loss: 0.6932 - accuracy: 0.5060 - val_loss: 0.6947 - val_accuracy: 0.5010
Epoch 3/5
782/782 [==============================] - 9s 12ms/step - loss: 0.6929 - accuracy: 0.5076 - val_loss: 0.6935 - val_accuracy: 0.5036
Epoch 4/5
782/782 [==============================] - 9s 11ms/step - loss: 0.6926 - accuracy: 0.5017 - val_loss: 0.6932 - val_accuracy: 0.5081
Epoch 5/5
782/782 [==============================] - 9s 12ms/step - loss: 0.6925 - accuracy: 0.5096 - val_loss: 0.6935 - val_accuracy: 0.5090


# Embedding

In [33]:
docs= ['go india',
       'india india',
       'hip hip hurray',
       'jeetega bhai jeetega india jeetega',
       'bharat mata ki jai',
       'sachin sachin',
       'Kohali kOhali',
       'modi ji ke jai',
       'jai hind'
      ]

In [34]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='mahavir')

In [35]:
tokenizer.fit_on_texts(docs)

In [36]:
tokenizer.word_index

{'mahavir': 1,
 'india': 2,
 'jeetega': 3,
 'jai': 4,
 'hip': 5,
 'sachin': 6,
 'kohali': 7,
 'go': 8,
 'hurray': 9,
 'bhai': 10,
 'bharat': 11,
 'mata': 12,
 'ki': 13,
 'modi': 14,
 'ji': 15,
 'ke': 16,
 'hind': 17}

In [39]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[8, 2],
 [2, 2],
 [5, 5, 9],
 [3, 10, 3, 2, 3],
 [11, 12, 13, 4],
 [6, 6],
 [7, 7],
 [14, 15, 16, 4],
 [4, 17]]

In [41]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 8,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 5,  5,  9,  0,  0],
       [ 3, 10,  3,  2,  3],
       [11, 12, 13,  4,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [14, 15, 16,  4,  0],
       [ 4, 17,  0,  0,  0]])

In [51]:
model = Sequential()

In [52]:
from keras.layers import Embedding 

In [53]:
model.add(Embedding(18,output_dim=2,input_length=5))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 5, 2)              36        
                                                                 
Total params: 36 (144.00 Byte)
Trainable params: 36 (144.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [54]:
model.compile('adam','accuracy')

In [55]:
pred = model.predict(sequences)

1/1 [==============================] - 0s 69ms/step


In [56]:
print(pred)

[[[ 0.02272977  0.01027333]
  [-0.01521374 -0.02080019]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]]

 [[-0.01521374 -0.02080019]
  [-0.01521374 -0.02080019]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]]

 [[-0.01242743 -0.04319127]
  [-0.01242743 -0.04319127]
  [-0.01381613  0.0036976 ]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]]

 [[ 0.03894985  0.03437677]
  [ 0.00121827 -0.01020874]
  [ 0.03894985  0.03437677]
  [-0.01521374 -0.02080019]
  [ 0.03894985  0.03437677]]

 [[-0.00382689 -0.02376651]
  [ 0.04280942  0.04550197]
  [-0.02959225  0.04313302]
  [-0.02848301 -0.00235983]
  [-0.0159786   0.01431589]]

 [[ 0.02502568 -0.03719218]
  [ 0.02502568 -0.03719218]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]]

 [[ 0.04038105  0.04027779]
  [ 0.04038105  0.04027779]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]
  [-0.0159786   0.01431589]]

 [[-0.

# Using Embedding on imdb dataset of keras

In [57]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

In [58]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

In [59]:
x_train = pad_sequences(x_train,padding='post',maxlen=50)
x_test = pad_sequences(x_test,padding='post',maxlen=50)

In [60]:
x_train.shape

(25000, 50)

In [68]:
x_train.max()

88585

In [72]:
model = Sequential()

model.add(Embedding(88586,output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 50, 2)             177172    
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 178325 (696.58 KB)
Trainable params: 178325 (696.58 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [73]:
model.compile(loss= 'binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [74]:
history = model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
782/782 [==============================] - 13s 15ms/step - loss: 0.6625 - accuracy: 0.5688 - val_loss: 0.4947 - val_accuracy: 0.7641
Epoch 2/5
782/782 [==============================] - 11s 14ms/step - loss: 0.4100 - accuracy: 0.8178 - val_loss: 0.4245 - val_accuracy: 0.8062
Epoch 3/5
782/782 [==============================] - 11s 14ms/step - loss: 0.2721 - accuracy: 0.8926 - val_loss: 0.4523 - val_accuracy: 0.8030
Epoch 4/5
782/782 [==============================] - 10s 13ms/step - loss: 0.1962 - accuracy: 0.9275 - val_loss: 0.5573 - val_accuracy: 0.7902
Epoch 5/5
782/782 [==============================] - 11s 14ms/step - loss: 0.1405 - accuracy: 0.9528 - val_loss: 0.6037 - val_accuracy: 0.7896
